### ISSUE TITLE
Output is null for Gitlab

### ISSUE THREAD

**Issue by VincentSC** [rgstephens/node-red-contrib-graphql#10]
To fix, add the word "Bearer" in `~/.node-red/node_modules/node-red-contrib-graphql/graphql.js`:  
> headers["Authorization"] = "Bearer " + node.graphqlConfig.authorization

In general a null-result is an authorization problem

**Comment by VincentSC** [comment]
Duh!! You can just add "Bearer " in the config :)

**Comment by VincentSC** [comment]
This doesn't work anymore. Have to use customHeaders to make it work. Looks like the authorization header is not even used.

**Comment by rgstephens** [comment]
`2.1.0` now supports bearer tokens in both the config node and the main node.

customHeaders is now documented
