### ISSUE TITLE
Please add a bit more documentation thank you

### ISSUE THREAD

**Issue by devleaks** [rgstephens/node-red-contrib-graphql#15]
This is a useful node contribution to hook node-red and graphql, very simple, very effective.
However I had to read the code to understand how it worked and how I could pass variables.
Thanks for your contribution and for adding a few notes.

**Comment by rgstephens** [comment]
Good idea, would be great for you to submit a PR on this.

**Comment by rgstephens** [comment]
Closed to PR [#16](https://github.com/rgstephens/node-red-contrib-graphql/pull/16)
