### ISSUE TITLE
Update npm from 0.2.5 to 0.18

### ISSUE THREAD

**Issue by moritz89** [rgstephens/node-red-contrib-graphql#19]
Hi, the last npm update is from a year and 3 months ago at version 0.2.5. Would it be possible to update it to be able to use 0.18 on NodeRED?

**Comment by rgstephens** [comment]
Sure, please submit a PR with the update and I'll merge.

**Comment by moritz89** [comment]
Sorry, was a bit confused about the versions. Everything already seems up to date
