### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jjpeet** [rgstephens/node-red-contrib-graphql#2]
Hi @rgstephens thanks for posting this node.

I have a need to get energy data from a GraphQL source but it uses authentication. I note that you haven't implemented this yet so I was wondering if you're aware of a way for me to use the standard http request node in Node-Red to send a GraphQL query and receive a response (until your node supports auth).

Using the GraphQL playground app I can successfully get the data I'm after, and also it provides me with a curl command, but trying to make this work in Node-Red so far has eluded me.
Any advice?

Thx
James

**Comment by rgstephens** [comment]
Hi @jjpeet, can you send a link to info on the interface and how it handles authentication. You can email me at greg@udon.org.

**Comment by eithe** [comment]
Hi @rgstephens, any chance you could finish the serviceTicket (x-auth-token) functionality? Would be great. I've worked my way around it temporary by just editing graphql.js locally and hard code in the header, but I'm not familiar enough with node-RED credentials to just go in and complete the functionality (looks like you are 90% there already :))

**Comment by adamgoose** [comment]
I just submitted #5, which allows you to specify a static Authorization header on the config node. Hopefully this will satisfy your needs, @eithe.

**Comment by SamuelToh** [comment]
Will be awesome if we can have some documentation around this...

Any idea how I can set the header? I have tried looking around the node and I can't see any potential spot to fill this information.

**Comment by stefanfejfar** [comment]
Hey, i have the same problem... I'd like to use oAuth2 Authentication, unfortunately I can't get it done.
Could you help or complete the Authorization Header feature?

**Comment by derFrickler** [comment]
Great!
Passing a Bearer Token via the Authorization Header field works fine. 
But is there a  to pass the Authorization Header to the node via variable or msg field as i get the token form another query before.

**Comment by rgstephens** [comment]
Addressed in PR #21
