### ISSUE TITLE
only log graphql request if enabled

### ISSUE THREAD

**Issue by wodka** [rgstephens/node-red-contrib-graphql#31]
it would be nice to only output the request + authorisation header if enabled.

https://github.com/rgstephens/node-red-contrib-graphql/blob/master/graphql.js#L362

Or as another option to log it with .debug

If you like I can create a PR

**Comment by rgstephens** [comment]
A PR would be great. Thanks.

**Comment by wodka** [comment]
:) finally did just that - I also added a change to the log print to exclude readables and buffers so the log message contains only useful information
