### ISSUE TITLE
Don't overwrite previous payload

### ISSUE THREAD

**Issue by VincentSC** [rgstephens/node-red-contrib-graphql#32]
Can `node.msg.payload.graphql` be used instead of `node.msg.payload`?

I can send in a PR with an extra configuration, so it's backwards compatible

**Comment by sys4cad** [comment]
overwrite previous payload is critical !!!
PLEASE FIX THIS URGENTLY

**Comment by VincentSC** [comment]
You mean that it's critical to overwrite or critical to *not* overwrite? :D

**Comment by sys4cad** [comment]
> You mean that it's critical to overwrite or critical to _not_ overwrite? :D

overwrite messaging actually means critical bug. you seems not understand its meaning at all.

**Comment by VincentSC** [comment]
> > You mean that it's critical to overwrite or critical to _not_ overwrite? :D
> 
> overwrite messaging actually means critical bug. you seems not understand its meaning at all.

You edited the original message to add "DON'T" *after* I asked my question, just 3 hours ago, and then blame me for everything. I now have zero interest in helping you now and share the fix with you. Have a good day

**Comment by sys4cad** [comment]
> > > You mean that it's critical to overwrite or critical to _not_ overwrite? :D
> > 
> > 
> > overwrite messaging actually means critical bug. you seems not understand its meaning at all.
> 
> You edited the original message to add "DON'T" _after_ I asked my question, just 3 hours ago, and then blame me for everything. I now have zero interest in helping you now and share the fix with you. Have a good day

you do whatever you want, but the reason I amended original comment is my 2nd language is not clearly state the problem.

Important thing is that bug makes huge compensated effort for the people use this component.
Sorry to hear your 0 interest to help this, but bug should be properly handled with professional manner. :)

**Comment by VincentSC** [comment]
@sys4cad Professional indeed. YOU CAN SHOUT LIKE A BAD MANAGER IN THE PULL REQUEST NOW, AND SEE IF THAT GETS YOU ANY FRIENDLY RESPONSE. :) https://github.com/rgstephens/node-red-contrib-graphql/pull/37

**Comment by sys4cad** [comment]
let me claify this chemical issue.
I misunderstand your question w/ :D as kind of cinical joke, and as I spent time and efforts to sort out this overwrite msg
issue my replies were not appropriate at all.
I'm sorry my lack of English communication skill makes you feel bad.

**Comment by sys4cad** [comment]
due to overwrite http response get wrong resoonse. 

나의 iPhone에서 보냄

**Comment by VincentSC** [comment]
Great! Can you ping here when npm is updated?

**Comment by rgstephens** [comment]
@VincentSC npm is updated!

**Comment by VincentSC** [comment]
Thanks!!

**Comment by VincentSC** [comment]
Tested, and found one problem:
```
              node.msg.payload = {}
```
on line 154.

I need to do more testing, but this one was an obvious one.

**Comment by VincentSC** [comment]
It seems to work with that one line removed

**Comment by rgstephens** [comment]
Good catch, fixed and updated in `2.1.1`.

**Comment by VincentSC** [comment]
Detail: it should be `if (!node.msg.payload) node.msg.payload = {};` :)

**Comment by rgstephens** [comment]
update

**Comment by VincentSC** [comment]
Explanation: you can always assume that `msg` exists, but not for `msg.payload` .

Sorry for the messy way of sharing fixes. I'll make sure that my branch gets updated later this month, so I can make better PRs including explanations and be sure I test them in full. I have some WIP for handling pagination, which I would like to share with you in a nice&tidy way
