### ISSUE TITLE
some special characters are converted by HTML Character Entity

### ISSUE THREAD

**Issue by sys4cad** [rgstephens/node-red-contrib-graphql#33]
I'm using this  graphql to load data
but unexpected transformation is applied as follows.

original data =>  ["WEATHER_TEMPERATURE","WEATHER_MOISTURE","WEATHER_HOT"]
![image](https://user-images.githubusercontent.com/9436271/146300085-be301e19-a3df-458a-8c7f-2c573865ea44.png)

result => [& quot;WEATHER_TEMPERATURE& quot;,& quot;WEATHER_MOISTURE&quot;,& quot;WEATHER_HOT& quot;]
![image](https://user-images.githubusercontent.com/9436271/146300146-9c193d45-74da-4a13-a352-cc6339032107.png)

Is there any way to resolve this conversion issue?
Thanks in advance.

**Comment by pwilimzig** [comment]
I have the same problem: "https://xxx.com" becomes "https:&#x2F;&#x2F;xxx.xom"

**Comment by marcometz** [comment]
I think the mustache template engine will convert your string.
Try to define the variables to not use HTML excapeing by this definition:

{{&company}} 

Details here:  https://github.com/janl/mustache.js/#variables

**Comment by pwilimzig** [comment]
Works perfectly! Thank you very much @marcometz
