### ISSUE TITLE
can debug be sent to the debug console, not console

### ISSUE THREAD

**Issue by sxsws** [rgstephens/node-red-contrib-graphql#36]
in a function, `node.log` sends to the console, but `node.warn()` upwards sends to the debug window. It would make more sense for the node's debug info to go to the debug pane.

**Comment by rgstephens** [comment]
This is how node-red works. There's a good discussion regarding this in the forum [here](https://discourse.nodered.org/t/how-to-debug-a-function-node/38024/3).
