### ISSUE TITLE
msg.payload is not loaded with query output

### ISSUE THREAD

**Issue by JohannChx** [rgstephens/node-red-contrib-graphql#46]
Hi,
Maybe I'm doing something wrong but the payload is never loaded with the query output.
Payload contains only the execution timestamp.
![Output_is_empty](https://user-images.githubusercontent.com/20836193/219051559-39aed9ba-7449-4762-abc1-db8893c155f7.JPG)
Thanks

**Comment by pinghe** [comment]
me too

**Comment by JohannChx** [comment]
Not a bug. In my example above, a timestamp (number) is injected in the flow. Thus, payload is not an object and graphql response cannot be added to it. Change Inject node to inject nothing or any object fixes the issue. 

![image](https://user-images.githubusercontent.com/20836193/221933309-ff37a05a-8cf1-4064-86bc-d39285553d4f.png)

**Comment by pinghe** [comment]
Thank you.

@JohannChx  Can you export and share the examples? I've never been able to figure out how to use Variable.

**Comment by JohannChx** [comment]
@pinghe, as explained in [README](https://github.com/rgstephens/node-red-contrib-graphql/blob/master/README.md), add your variables in msg, for example with a inject node :
![image](https://user-images.githubusercontent.com/20836193/222079743-1cda1c39-df6c-4d26-8417-49b678366c4e.png)

**Comment by kyuumeitai** [comment]
Thank you, this could be in the readme IMHO.
