### ISSUE TITLE
Output is null

### ISSUE THREAD

**Issue by Swiftnesses** [rgstephens/node-red-contrib-graphql#8]
Hello,

I've entered all my server details (inc auth header) and performed a simple query, sadly the payload output is null (it does show 'success". The payload is populated with the right top level name, but the value is null?

<img width="281" alt="Screenshot 2019-11-03 at 11 01 02" src="https://user-images.githubusercontent.com/1001877/68084118-41a5a600-fe29-11e9-9e27-0ac3f3cb2f49.png">

**Comment by Swiftnesses** [comment]
Seems I need an 'Origin' header, what is the best way to add this to the request?

**Comment by VincentSC** [comment]
Same here, on Gitlab. did you find out what needed to be done?

**Comment by rgstephens** [comment]
The output issue was fixed some time ago (not sure what release but at least 1.4.1)

The `Origin` header can be done with `customHeaders` which is now documented [here](https://github.com/rgstephens/node-red-contrib-graphql#custom-headers).
